### ISSUE TITLE
Usage of RocketChatQueryParams

### ISSUE THREAD

**Issue by Canos** [baloise/rocket-chat-rest-client#57] opened 2020-06-22 09:38 UTC
I'm trying to use RocketChatQueryParams to get a channels list.
Unfortunately i dont know how to use params api.

i have tried:
```java
            params.add("name", name);
            params.add("name", "{ \"$regex\": "+name+" }");
```

but it always returns all channels created.

any tip or example?

**Comment by fdbatista** [comment] 2020-06-22 19:46
Hi, @Canos.
I might be in a very similar situation.

Fetching the list of channels should not require any query parameters, but when I do `channelsApi.list()` I get a serialization error. I don't know if you are going through the same, but it looks like this library might not work with all RocketChat versions.

I tried then to set the query parameters for paginating the results and I got rid of the serialization error, but now I always get the first page:

```java
var queryParams = new RocketChatQueryParams();
queryParams.add("count", "20");
queryParams.add("offset", "0");
queryParams.add("sort", "{\"name\": 1}");
```

It always returns the first page, no matter what offset I define (0, 1, 2, 3...).
Maybe you could try to do the same, to see if you can reproduce the same situation.

**Comment by col-panic** [comment] 2020-08-04 08:41
In https://github.com/baloise/rocket-chat-rest-client/blob/d8a964c3a1cc4e31fd124dfd4f09493fc57ca1aa/src/main/java/com/github/baloise/rocketchatrestclient/RocketChatRestApiV1Channels.java#L312 you find a sample on how I use the query parameter to limit the list of channels by its name.

**Comment by col-panic** [comment] 2020-11-25 11:31
Closing this as no further response.

**Closed as completed by col-panic** 2020-11-25 11:31 UTC
